[install]
is_configured = 0
state = enabled
check_for_updates = 1

[package]
check_for_updates = 1
id = TA-trellix-epo

[ui]
is_visible = 1
label = Trellix ePO Add-on

[launcher]
author = Splunk Add-on Developer
description = Technology Add-on for Trellix (McAfee) ePO - Ingests security telemetry and normalizes to CIM
version = 1.0.0

[id]
name = TA-trellix-epo
version = 1.0.0

[triggers]
reload.addon = simple
reload.ta_trellix_epo_settings = simple
reload.ta_trellix_epo_inputs = simple

[logging]
level = INFO

