# REST API endpoint configuration for Trellix ePO Add-on
# Defines admin handlers for settings and inputs management

[admin:ta_trellix_epo]
match = /ta_trellix_epo
members = ta_trellix_epo_settings, ta_trellix_epo_inputs

[admin_external:ta_trellix_epo_settings]
handlertype = python
python.version = python3
handlerfile = ta_trellix_epo_rh_settings.py
handleractions = edit, list, create, remove
handlerpersistentmode = true

[admin_external:ta_trellix_epo_inputs]
handlertype = python
python.version = python3
handlerfile = ta_trellix_epo_rh_inputs.py
handleractions = edit, list, create, remove
handlerpersistentmode = true
