[admin:ta_trellix_epo]
pattern = ta_trellix_epo_*
members = ta_trellix_epo_settings, ta_trellix_epo_inputs

[admin_external:ta_trellix_epo_settings]
handlertype = python
python.version = python3
handlerfile = ta_trellix_epo_rh_settings.py
handleractions = edit, list, create, remove
handlerpersistent = True

[admin_external:ta_trellix_epo_inputs]
handlertype = python
python.version = python3
handlerfile = ta_trellix_epo_rh_inputs.py
handleractions = edit, list, create, remove
handlerpersistent = True
